keywords: >- 
  Edmonton, web design, software development, startup, technology, IT consulting,
  NAIT graduates, Digital Media and IT, SEO services, Social Media Marketing,
  Custom software solution, Application development, mobile development 

url: https://www.polysoft.ca
email: 

exclude: 
  - _designs
  - Gemfile
  - Gemfile.lock
    
defaults:
  - # layout: default
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap