keywords: >-

url: https://www.polysoft.ca
phone: 
email: 

exclude: 
  - _designs
  - Gemfile
  - Gemfile.lock
    
defaults:
  - # layout: default
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap